version: 2.1

commands:
  npm_install:
    steps:
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - npm_install
      - run: npm run lint
      - run: npm run build
      - run: npm run test:unit
